# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-23 00:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Record',
            fields=[
                ('admin_id', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, max_length=255)),
                ('version', models.CharField(blank=True, default=None, max_length=255)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='AOI_Data_Record',
            fields=[
                ('aoi_data_id', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('aoi', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('t', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'aoi_data',
            },
        ),
        migrations.CreateModel(
            name='AOI_Region_Record',
            fields=[
                ('aoi_region_id', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('l_x_max', models.IntegerField(blank=True, default=None, null=True)),
                ('l_x_min', models.IntegerField(blank=True, default=None, null=True)),
                ('l_y_max', models.IntegerField(blank=True, default=None, null=True)),
                ('l_y_min', models.IntegerField(blank=True, default=None, null=True)),
                ('r_x_max', models.IntegerField(blank=True, default=None, null=True)),
                ('r_x_min', models.IntegerField(blank=True, default=None, null=True)),
                ('r_y_max', models.IntegerField(blank=True, default=None, null=True)),
                ('r_y_min', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'aoi_regions',
            },
        ),
        migrations.CreateModel(
            name='Dataset_Record',
            fields=[
                ('dataset_id', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('monitor_size_x', models.IntegerField(blank=True, default=None, null=True)),
                ('monitor_size_y', models.IntegerField(blank=True, default=None, null=True)),
                ('sample_rate', models.IntegerField(blank=True, default=None, null=True)),
                ('tracker', models.IntegerField(blank=True, default=None, null=True)),
                ('lab_dataset_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'datasets',
            },
        ),
        migrations.CreateModel(
            name='Subject_Record',
            fields=[
                ('subject_id', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('sex', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('lab_subject_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Trial_Record',
            fields=[
                ('trial_id', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('lab_trial_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('distractor_image', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('distractor_label', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('full_phrase', models.IntegerField(blank=True, default=None, null=True)),
                ('point_of_disambiguation', models.IntegerField(blank=True, default=None, null=True)),
                ('target_image', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('target_label', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('target_side', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('aoi_region', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='db.AOI_Region_Record')),
                ('dataset', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='db.Dataset_Record')),
            ],
            options={
                'db_table': 'trials',
            },
        ),
        migrations.CreateModel(
            name='XY_Data_Record',
            fields=[
                ('xy_data_id', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('x', models.IntegerField(blank=True, default=None, null=True)),
                ('y', models.IntegerField(blank=True, default=None, null=True)),
                ('subject', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='db.Subject_Record')),
                ('trial', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='db.Trial_Record')),
            ],
            options={
                'db_table': 'xy_data',
            },
        ),
        migrations.AddField(
            model_name='aoi_data_record',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='db.Subject_Record'),
        ),
        migrations.AddField(
            model_name='aoi_data_record',
            name='trial',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='db.Trial_Record'),
        ),
    ]
