# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-09 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xy_timepoint',
            old_name='t',
            new_name='t_norm',
        ),
    ]
