# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-22 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset_record',
            name='lab_dataset_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subject_record',
            name='lab_subject_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
