# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-23 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial_record',
            name='aoi_region',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
