# Generated by Django 5.1.6 on 2025-04-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20201209_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='administration_aux_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='dataset_aux_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='stimulus',
            name='image_description',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stimulus',
            name='image_description_source',
            field=models.CharField(choices=[('image path', 'image path'), ('experiment documentation', 'experiment documentation'), ('Peekbank discretion', 'Peekbank discretion')], default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stimulus',
            name='stimulus_aux_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_aux_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='excluded',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='exclusion_reason',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='trial_aux_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='trial_type',
            name='trial_type_aux_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='trial_type',
            name='vanilla_trial',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='administration',
            name='coding_method',
            field=models.CharField(choices=[('eyetracking', 'eyetracking'), ('manual gaze coding', 'manual gaze coding'), ('automated gaze coding', 'automated gaze coding'), ('preprocessed eyetracking', 'preprocessed eyetracking')], default=None, max_length=255, null=True),
        ),
    ]
