# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-22 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20190822_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial_record',
            name='lab_trial_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
