download=python manage.py download
populate=python manage.py populate
promote=python manage.py promote
export=python manage.py export
import=python manage.py import
mirror=python manage.py mirror
backup=python manage.py backup
latest=./create_latest.sh